apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bloboutput
spec:
  name: bloboutput
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: dserverless1
  - name: storageAccessKey
    value: "YSBLEB9cMU3ouDq5cVNClY1mGoNWOeO+mksAAWdJ66Cb1nv+6byPvza/tWtEE/7qUjG7wytMGLYGxUCYpaKWpQ=="
  - name: container
    value: items
  - name: decodeBase64
    value: "true"