apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: queueinput
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: storageAccount
    value: "{.storageAccount}"
  - name: storageAccessKey
    value: "{.storageAccessKey}"
  - name: queue
    value: requests
  - name: ttlInSeconds
    value: 60
  - name: decodeBase64
    value: "true"